### ISSUE TITLE
配置好环境docker运行出错

### ISSUE THREAD

**Issue by Echozxc** [qiaoborui/wzxyNew#1]
2024-03-17 22:23:19,288 - INFO - Welcome to Wozaixiaoyuan Night Sign-in Script!
2024-03-17 22:23:19,288 - INFO - Next scheduled run time: 2024-03-17 22:25:00
2024-03-17 22:25:00,100 - INFO - Running user 刘...
2024-03-17 22:25:00,100 - ERROR - No JWSESSION found in local cache, starting login...
2024-03-17 22:25:02,104 - ERROR - An error occurred while running user 刘: HTTPSConnectionPool(host='gw.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /basicinfo/mobile/login/username?schoolId=61&username=13177887967&password=RFyeejDrz9QV0FspBzgoTg%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe3fe058310>: Failed to resolve 'gw.wozaixiaoyuan.com' ([Errno -3] Try again)"))
2024-03-17 22:25:02,106 - ERROR - Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
sock = connection.create_connection(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 793, in urlopen
response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
raise new_e
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 616, in connect
self.sock = sock = self._new_conn()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in _new_conn
raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fe3fe058310>: Failed to resolve 'gw.wozaixiaoyuan.com' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 847, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gw.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /basicinfo/mobile/login/username?schoolId=61&username=13177887967&password=RFyeejDrz9QV0FspBzgoTg%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe3fe058310>: Failed to resolve 'gw.wozaixiaoyuan.com' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/app/./wzxy.py", line 217, in run_users
u = User(user_data.get('username'), user_data.get('password'), user_data.get('school_id'))
File "/usr/src/app/./wzxy.py", line 43, in __init__
self.test_cached_session()
File "/usr/src/app/./wzxy.py", line 132, in test_cached_session
if self.login():
File "/usr/src/app/./wzxy.py", line 60, in login
login_req = requests.post(login_url, params=params)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gw.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /basicinfo/mobile/login/username?schoolId=61&username=13177887967&password=RFyeejDrz9QV0FspBzgoTg%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe3fe058310>: Failed to resolve 'gw.wozaixiaoyuan.com' ([Errno -3] Try again)"))
请问作者大大我是哪里出错了吗

**Comment by Echozxc** [comment]
终端里运行py报错：
[root@Eternity wzxy]# python wzxy.py
  File "wzxy.py", line 69
    logging.error(f"{self.username} login error, please check account password!")
SyntaxError: invalid syntax
但是config.ini文件里的用户名和密码都没有写错

**Comment by qiaoborui** [comment]
> 终端里运行py报错：
> 
> [root@Eternity wzxy]# python wzxy.py
> 
>   File "wzxy.py", line 69
> 
>     logging.error(f"{self.username} login error, please check account password!")
> 
> SyntaxError: invalid syntax
> 
> 但是config.ini文件里的用户名和密码都没有写错

抱歉回复的晚了
可能存在的原因有：
- 如果是在云服务器，可能ip段被我在校园官方封禁
- 有可能学校id与实际不匹配，可以自行抓包查看
加密方式应该是全国通用，能否提供配置文件以供复现
Mr.Strawberry@outlook.com

**Comment by Echozxc** [comment]
> > 终端里运行py报错：
> > [root@Eternity wzxy]# python wzxy.py
> > File "wzxy.py", line 69 文件“wzxy.py”，第 69 行
> > ```
> > logging.error(f"{self.username} login error, please check account password!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > SyntaxError: invalid syntax SyntaxError：语法无效
> > 但是config.ini文件里的用户名和密码都没有写错
> 
> 抱歉回复的晚了 可能存在的原因有：
> 
> * 如果是在云服务器，可能ip段被我在校园官方封禁
> * 有可能学校id与实际不匹配，可以自行抓包查看
>   加密方式应该是全国通用，能否提供配置文件以供复现
>   [Mr.Strawberry@outlook.com Mr.Strawberry@outlook.com](mailto:Mr.Strawberry@outlook.com)

已提供

**Comment by qiaoborui** [comment]
<img width="1150" alt="截屏2024-03-20 21 57 31" src="https://github.com/qiaoborui/wzxyNew/assets/39862938/2565dcec-7844-4018-b78a-c14ee6b69492">
登陆成功
是我的失误，请重新查看最新的readme，配置文件不是ini格式，而是toml格式，并且新增了cron expression配置项，用于不同时间的打卡需求，感谢反馈
